# Generated by Django 5.1.4 on 2025-01-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('api_key', models.CharField(max_length=200)),
            ],
        ),
    ]
