# Generated by Django 5.1.4 on 2025-01-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_api_key_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feed_token',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Feed Token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Username'),
        ),
    ]
