# Generated by Django 5.1.4 on 2025-01-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=150)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('expiry', models.CharField(blank=True, max_length=50, null=True)),
                ('strike', models.FloatField(blank=True, null=True)),
                ('lotsize', models.IntegerField(blank=True, null=True)),
                ('instrumenttype', models.CharField(blank=True, max_length=50, null=True)),
                ('exch_seg', models.CharField(max_length=10)),
                ('tick_size', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'instruments',
            },
        ),
    ]
