# Generated by Django 5.1.4 on 2025-01-08 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['symbol'], name='instruments_symbol_21d3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['token'], name='instruments_token_29cc3c_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['exch_seg'], name='instruments_exch_se_9e08f1_idx'),
        ),
    ]
