# Generated by Django 5.1.4 on 2025-01-09 06:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_instrument_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('open', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Opening Price')),
                ('high', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='High Price')),
                ('low', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Low Price')),
                ('close', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Closing Price')),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Last Traded Price')),
                ('volume', models.BigIntegerField(default=0, verbose_name='Trading Volume')),
                ('atp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Average Traded Price')),
                ('open_interest', models.BigIntegerField(default=0, verbose_name='Open Interest')),
                ('total_buy_quantity', models.BigIntegerField(default=0, verbose_name='Total Buy Quantity')),
                ('total_sell_quantity', models.BigIntegerField(default=0, verbose_name='Total Sell Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlc_data', to='trading.instrument')),
            ],
            options={
                'verbose_name': 'OHLC Data',
                'verbose_name_plural': 'OHLC Data',
                'db_table': 'ohlc_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', 'timestamp'], name='ohlc_data_instrum_ab20eb_idx'), models.Index(fields=['timestamp'], name='ohlc_data_timesta_3b0347_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradeSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('EXIT', 'Exit')], max_length=10, verbose_name='Signal Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Signal Price')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Signal Time')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='trading.instrument')),
            ],
            options={
                'verbose_name': 'Trade Signal',
                'verbose_name_plural': 'Trade Signals',
                'db_table': 'trade_signals',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', 'timestamp'], name='trade_signa_instrum_d30a9d_idx'), models.Index(fields=['signal_type'], name='trade_signa_signal__68801a_idx'), models.Index(fields=['is_active'], name='trade_signa_is_acti_0ec301_idx')],
            },
        ),
    ]
